# Generated by Django 4.2.2 on 2023-07-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_alter_listing_home_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='open_house',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='slug',
        ),
    ]
